BakeryPierre/Models/Treat.cs
using System.Collections.Generic;

namespace BakeryPierre.Models
{
  public class Treat
  {
    public Treat()
    {
      this.Flavors = new HashSet<FlavorTreat>();
    }
    public int TreatId { get; set; }
    public string TreatName { get; set; }
    public bool AvailableToday { get; set; } 
    public float Price { get; set; }
    public virtual ApplicationUser User { get; set; }
    public ICollection<FlavorTreat> Flavors { get; }
  }
}

BakeryPierre/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc;
using BakeryPierre.Models;
using System.Collections.Generic;
using System.Linq;
using System;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace BakeryPierre.Controllers
{
  public class TreatsController : Controller
  {
    private readonly BakeryPierreContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public TreatsController(UserManager<ApplicationUser> userManager, BakeryPierreContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public async Task<ActionResult> Index(string sortOrder, string searchString)
    {
      ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
      ViewBag.PriceSortParm = String.IsNullOrEmpty(sortOrder) ? "price_desc" : "";
      var treats = from treat in _db.Treats select treat;
      if (!String.IsNullOrEmpty(searchString))
      {
          treats = treats.Where(treat => treat.TreatName.Contains(searchString));
      }
      switch (sortOrder)
      {
        case "name_desc":
          treats = treats.OrderByDescending(treat => treat.TreatName);
          break;
        case "price_desc":
          treats = treats.OrderByDescending(treat => treat.Price);
          break;
        default:
          treats = treats.OrderBy(treat => treat.TreatName);
          break;
      }
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      return View(treats.ToList());
    }

    [Authorize]
    public ActionResult Create()
    {
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Treat treat, int FlavorId)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      treat.User = currentUser;
      _db.Treats.Add(treat);
      if (FlavorId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      var thisTreat = _db.Treats
          .Include(treat => treat.Flavors)
          .ThenInclude(join => join.Flavor)
          .Include(treat => treat.User)
          .FirstOrDefault(treat => treat.TreatId == id);
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ViewBag.IsCurrentUser = userId != null ? userId == thisTreat.User.Id : false;
      return View(thisTreat);
    }

       [Authorize]
    public async Task<ActionResult> Edit(int id)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var thisTreat = _db.Treats.Where(entry => entry.User.Id == currentUser.Id).FirstOrDefault(treats => treats.TreatId == id);
      if (thisTreat == null)
      {
        return RedirectToAction("Details", new {id = id});
      }
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult Edit(Treat treat, int FlavorId)
    {
      if (FlavorId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
      }
      _db.Entry(treat).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    public async Task<ActionResult> Delete(int id)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var thisTreat = _db.Treats.Where(entry => entry.User.Id == currentUser.Id).FirstOrDefault(treats => treats.TreatId == id);
      if (thisTreat == null)
      {
        return RedirectToAction("Details", new {id = id});
      }
      return View(thisTreat);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    public async Task<ActionResult> AddFlavor(int id)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var thisTreat = _db.Treats.Where(entry => entry.User.Id == currentUser.Id).FirstOrDefault(treats => treats.TreatId == id);
      if (thisTreat == null)
      {
        return RedirectToAction("Details", new {id = id});
      }
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int FlavorId)
    {
      if (FlavorId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteFlavor(int joinId)
    {
      var joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

BakeryPierre/Views/Treats/AddFlavor.cshtml
@model BakeryPierre.Models.Treat

@{
  Layout = "_Layout";
}

<h2>Add a Flavor</h2>

<h4>Add a flavor profile to this treat: @Html.DisplayFor(model => model.TreatName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)

  @Html.Label("Select Flavor")
  @Html.DropDownList("FlavorId")

  <input type="submit" value="Save" />
}

BakeryPierre/Views/Treats/Create.cshtml
@model BakeryPierre.Models.Treat

@{
  Layout = "_Layout";
}

<h2>Add a new Treat</h2>

@using(Html.BeginForm())
{
  <div class="row">
    <div class="col-md-5 column">
      @Html.LabelFor(model => model.TreatName)<br>
    </div>
    <div class="col-md-5 column">
      @Html.TextBoxFor(model => model.TreatName, new {@class="form-control", required="required"})<br>
    </div>
  </div>
  <div class="row">
    <div class="col-md-5 column">
      @Html.Label("Treat is available today :")<br>
    </div>
    <div class="col-md-5 column">
      @Html.CheckBoxFor(model => model.AvailableToday, true)<br>
    </div>
  </div>
  <div class="row">
    <div class="col-md-5 column">
        @Html.LabelFor(model => model.Price)<br>
    </div>
    <div class="col-md-5 column">
        @Html.TextBoxFor(model => model.Price, new { @type = "number", step="any"})<br>
    </div>
  </div>
  <div class="row">
    <div class="col-md-5 column">
      @Html.Label("Flavor profile of this treat ")<br>
    </div>
    <div class="col-md-5 column">
      @Html.DropDownList("FlavorId", "Select")<br>
      <br>    
      <input type="submit" value="Add Treat" /><br>
    </div>
  </div>
}

BakeryPierre/Views/Treats/Delete.cshtml
@model BakeryPierre.Models.Treat

@{
  Layout = "_Layout";
}

<h2>Are you sure you want to delete this treat?</h2>

@Html.DisplayName("Flavor"): @Html.DisplayFor(model => model.TreatName)

@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

BakeryPierre/Views/Treats/Details.cshtml
@{
  Layout = "_Layout";
}

@using System.Security.Claims
@model BakeryPierre.Models.Treat

<h2>Treat Details</h2>
<hr />

<h3>@Html.Label("Treat "): @Html.DisplayFor(model => model.TreatName)<h3>

@if(@Model.Flavors.Count == 0)
{
  <p>This treat is not assigned a flavor profile</p>
}
else
{
  <h4>Flavor profile of this Treat:</h4>
  <ul>
    @foreach(var join in Model.Flavors)
    {
      <li>@join.Flavor.FlavorName</li>
      @if(User.Identity.IsAuthenticated && ViewBag.IsCurrentUser)
      {
        @using (Html.BeginForm("DeleteFlavor", "Treats"))
        {
          @Html.Hidden("joinId", @join.FlavorTreatId)
          <input type="submit" value="Delete" />
        }
      }
    }
  </ul>
}

@if (User.Identity.IsAuthenticated && ViewBag.IsCurrentUser)
{
  <p>@Html.ActionLink("Edit Treat", "Edit", new { id = Model.TreatId })</p>
  <p>@Html.ActionLink("Delete Treat", "Delete", new { id = Model.TreatId })</p>
  <p>@Html.ActionLink("Add a Flavor Profile", "AddFlavor", new { id = Model.TreatId })</p>
}

BakeryPierre/Views/Treats/Edit.cshtml
@model BakeryPierre.Models.Treat

@{
  Layout = "_Layout";
}

<h2>Edit this Treat : @Html.DisplayFor(model => model.TreatName)</h2>

@using(Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)
  <div class="row">
    <div class="col-md-5 column">
      @Html.LabelFor(model => model.TreatName)<br>
    </div>
    <div class="col-md-5 column">
      @Html.EditorFor(model => model.TreatName, new {@class="form-control", required="required"})<br>
    </div>
  </div>
  <div class="row">
    <div class="col-md-5 column">
      @Html.Label("Treat is available today :")<br>
    </div>
    <div class="col-md-5 column">
      @Html.CheckBoxFor(model => model.AvailableToday, true)<br>
    </div>
  </div>
  <div class="row">
    <div class="col-md-5 column">
        @Html.LabelFor(model => model.Price)<br>
    </div>
    <div class="col-md-5 column">
        @Html.EditorFor(model => model.Price, new { @type = "number", step="any"})<br>
    </div>
  </div>
  <div class="row">
    <div class="col-md-5 column">
      @Html.Label("Flavor profile of this treat ")<br>
    </div>
    <div class="col-md-5 column">
      @Html.DropDownList("FlavorId", "Select")<br>
      <br>    
      <input type="submit" value="Save" /><br>
    </div>
  </div>
}

BakeryPierre/Views/Treats/Index.cshtml
@using BakeryPierre.Models;
@model List<BakeryPierre.Models.Treat>;

@{
  Layout = "_Layout";
}

<h1>Treats</h1>
<hr/>

@if (@Model.Count == 0)
{
  <h5>There are no treats in the system</h5>
}
else
{
  @using (Html.BeginForm())
  {
    <p> 
      Find by name: @Html.TextBox("SearchString")
      <input type="submit" value="Search" />
    </p>
  }
  <table class="table">
    <tr>
        <th>
            @Html.ActionLink("Treat", "Index", new { sortOrder = ViewBag.NameSortParm })
        </th>
        <th>
            Available Today
        </th>
        <th>
            @Html.ActionLink("Price", "Index", new { sortOrder = ViewBag.PriceSortParm })
        </th>
    </tr>
    
  @foreach (Treat treat in @Model)
  {
    <tr>
      <td>
        @Html.ActionLink($"{treat.TreatName}", "Details", new { id = treat.TreatId})
      </td>
      <td>
        @treat.AvailableToday
      </td>
      <td>
        @treat.Price
      </td>
    </tr>
  }
  </table>
}

@if (User.Identity.IsAuthenticated)
{
  <p>@Html.ActionLink("Add new Treat", "Create")</p>
}