BakeryPierre/Models/Flavor.cs
using System.Collections.Generic;

namespace BakeryPierre.Models
{
  public class Flavor
  {
    public Flavor()
    {
      this.Treats = new HashSet<FlavorTreat>();
    }
    public int FlavorId { get; set; }
    public string FlavorName { get; set; }
    public virtual ApplicationUser User { get; set; }
    public ICollection<FlavorTreat> Treats { get; set; }
  }
}

BakeryPierre/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc;
using BakeryPierre.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace BakeryPierre.Controllers
{
  public class FlavorsController : Controller
  {
    private readonly BakeryPierreContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public FlavorsController(UserManager<ApplicationUser> userManager, BakeryPierreContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public async Task<ActionResult> Index()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      List<Flavor> userFlavors = _db.Flavors.ToList();
      return View(userFlavors);
    }

    [Authorize]
    public ActionResult Create()
    {
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "TreatName");
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Flavor flavor, int TreatId)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      flavor.User = currentUser;
      _db.Flavors.Add(flavor);
      if (TreatId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { TreatId = TreatId, FlavorId = flavor.FlavorId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      var thisFlavor = _db.Flavors
          .Include(flavor => flavor.Treats)
          .ThenInclude(join => join.Treat)
          .Include(flavor => flavor.User)
          .FirstOrDefault(flavor => flavor.FlavorId == id);
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ViewBag.IsCurrentUser = userId != null ? userId == thisFlavor.User.Id : false;
      return View(thisFlavor);
    }

    [Authorize]
    public async Task<ActionResult> Edit(int id)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var thisFlavor = _db.Flavors.Where(entry => entry.User.Id == currentUser.Id).FirstOrDefault(flavors => flavors.FlavorId == id);
      if (thisFlavor == null)
      {
        return RedirectToAction("Details", new {id = id});
      }
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "TreatName");
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult Edit(Flavor flavor, int TreatId)
    {
      if (TreatId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { TreatId = TreatId, FlavorId = flavor.FlavorId });
      }
      _db.Entry(flavor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    public async Task<ActionResult> Delete(int id)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var thisFlavor = _db.Flavors.Where(entry => entry.User.Id == currentUser.Id).FirstOrDefault(flavors => flavors.FlavorId == id);
      if (thisFlavor == null)
      {
        return RedirectToAction("Details", new {id = id});
      }
      return View(thisFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    public async Task<ActionResult> AddTreat(int id)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var thisFlavor = _db.Flavors.Where(entry => entry.User.Id == currentUser.Id).FirstOrDefault(flavors => flavors.FlavorId == id);
      if (thisFlavor == null)
      {
        return RedirectToAction("Details", new {id = id});
      }
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "TreatName");
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult AddTreat(Flavor flavor, int TreatId)
    {
      if (TreatId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { TreatId = TreatId, FlavorId = flavor.FlavorId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteTreat(int joinId)
    {
      var joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

  
  }
}

BakeryPierre/Views/Flavors/AddTreat.cshtml
@model BakeryPierre.Models.Flavor

@{
  Layout = "_Layout";
}

<h2>Add a Treat</h2>

<h4>Add a treat with this flavor profile: @Html.DisplayFor(model => model.FlavorName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)

  @Html.Label("Select Treat")
  @Html.DropDownList("TreatId")

  <input type="submit" value="Save" />
}

BakeryPierre/Views/Flavors/Create.cshtml
@model BakeryPierre.Models.Flavor

@{
  Layout = "_Layout";
}

<h2>Add a new Flavor</h2>

@using(Html.BeginForm())
{
  <div class="row">
    <div class="col-md-5 column">
      @Html.LabelFor(model => model.FlavorName)<br>
    </div>
    <div class="col-md-5 column">
      @Html.TextBoxFor(model => model.FlavorName, new {@class="form-control", required="required"})<br>
    </div>
  </div>
  <div class="row">
    <div class="col-md-5 column">
      @Html.Label("Treats with this Flavor ")<br>
    </div>
    <div class="col-md-5 column">
      @Html.DropDownList("TreatId", "Select")<br>
      <br>    
      <input type="submit" value="Add Flavor" /><br>
    </div>
  </div>
}

BakeryPierre/Views/Flavors/Delete.cshtml
@model BakeryPierre.Models.Flavor

@{
  Layout = "_Layout";
}

<h2>Are you sure you want to delete this flavor?</h2>

@Html.DisplayName("Flavor"): @Html.DisplayFor(model => model.FlavorName)

@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

BakeryPierre/Views/Flavors/Details.cshtml
@{
  Layout = "_Layout";
}

@using System.Security.Claims
@model BakeryPierre.Models.Flavor

<h2>Flavor Details</h2>
<hr />

<h3>@Html.Label("Flavor "): @Html.DisplayFor(model => model.FlavorName)<h3>

@if(@Model.Treats.Count == 0)
{
  <p>This flavor is not associated with any treats</p>
}
else
{
  <h4>Treats that have this flavor profile:</h4>
  <ul>
    @foreach(var join in Model.Treats)
    {
      <li>@join.Treat.TreatName</li>
      @if(User.Identity.IsAuthenticated && ViewBag.IsCurrentUser)
      {
        @using (Html.BeginForm("DeleteTreat", "Flavors"))
        {
          @Html.Hidden("joinId", @join.FlavorTreatId)
          <input type="submit" value="Delete" />
        }
      }
    }
  </ul>
}

@if (User.Identity.IsAuthenticated && ViewBag.IsCurrentUser)
{
  <p>@Html.ActionLink("Edit Flavor", "Edit", new { id = Model.FlavorId })</p>
  <p>@Html.ActionLink("Delete Flavor", "Delete", new { id = Model.FlavorId })</p>
  <p>@Html.ActionLink("Add a Treat", "AddTreat", new { id = Model.FlavorId })</p>
}

BakeryPierre/Views/Flavors/Edit.cshtml
@model BakeryPierre.Models.Flavor

@{
  Layout = "_Layout";
}

<h2>Edit this Flavor : @Html.DisplayFor(model => model.FlavorName)</h2>

@using(Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)
  <div class="row">
    <div class="col-md-5 column">
      @Html.LabelFor(model => model.FlavorName)<br>
    </div>
    <div class="col-md-5 column">
      @Html.EditorFor(model => model.FlavorName, new {@class="form-control", required="required"})<br>
    </div>
  </div>
  <div class="row">
    <div class="col-md-5 column">
      @Html.Label("Treats with this Flavor ")<br>
    </div>
    <div class="col-md-5 column">
      @Html.DropDownList("TreatId", "Select")<br>
      <br>    
      <input type="submit" value="Add Flavor" /><br>
    </div>
  </div>
}

BakeryPierre/Views/Flavors/Index.cshtml
@using BakeryPierre.Models;
@model List<BakeryPierre.Models.Flavor>;

@{
  Layout = "_Layout";
}

<h1>Flavors</h1>
<hr/>

@if (@Model.Count == 0)
{
  <h3>No flavors have been added yet</h3>
}

@foreach (Flavor flavor in Model)
{
  <li>@Html.ActionLink($"{flavor.FlavorName}", "Details", new { id = flavor.FlavorId})</li>
}

@if (User.Identity.IsAuthenticated)
{
 <p>@Html.ActionLink("Add new Flavor", "Create")</p>
}